name:       generative-art
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:     David »quchen« Luposchainsky – dluposchainsky (λ) gmail
maintainer: David »quchen« Luposchainsky – dluposchainsky (λ) gmail
copyright:  "2018 David Luposchainsky"

extra-source-files:
    - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: Generative art using Haskell. See README.md.

dependencies:
    - base >= 4.7 && < 5
    - cairo
    - colour
    - containers
    - data-default-class
    - mwc-random
    - random
    - transformers
    - vector

ghc-options:
    - -Wall
    - -Wno-type-defaults

library:
    source-dirs: src

executables:
    haskell-logo-billard:
        main:        Main.hs
        source-dirs: app/haskell_logo_billard
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -Wno-type-defaults
        dependencies:
            - generative-art
            - cairo
    haskell-logo-triangles:
        main:        Main.hs
        source-dirs: app/haskell_logo_triangles
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -Wno-type-defaults
        dependencies:
            - generative-art
            - cairo
            - random
            - transformers
            - containers
    vector-fields:
        main: Main.hs
        source-dirs: app/vector_fields
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -Wno-type-defaults
        dependencies:
            - generative-art
            - cairo
            - hsnoise
            - mwc-random
    haskell-logo-voronoi:
        main: Main.hs
        source-dirs: app/haskell_logo_voronoi
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -Wno-type-defaults
        dependencies:
            - generative-art
            - cairo
            - mwc-random
    voronoi-interactive:
        main: Main.hs
        source-dirs: app/voronoi_interactive
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -Wno-type-defaults
        dependencies:
            - generative-art
            - cairo
            - threepenny-gui
            - mwc-random


tests:
    generative-art-test:
        main:        Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -Wno-type-defaults
        dependencies:
            - generative-art

            - cairo
            - process
            - QuickCheck
            - random
            - tasty
            - tasty-hunit
            - tasty-quickcheck
            - transformers
