name:       generative-art
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:     David »quchen« Luposchainsky – dluposchainsky (λ) gmail
maintainer: David »quchen« Luposchainsky – dluposchainsky (λ) gmail
copyright:  "2018 David Luposchainsky"

extra-source-files:
    - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Generative art using Haskell.

dependencies:
    - base >= 4.7 && < 5
    - cairo
    - colour

ghc-options:
    - -Wall

library:
    source-dirs: src

executables:
    haskell-logo-billard:
        main:        Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
        dependencies:
            - generative-art
            - cairo

tests:
    generative-art-test:
        main:        Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
        dependencies:
            - generative-art

            - cairo
            - process
            - QuickCheck
            - tasty
            - tasty-hunit
            - tasty-quickcheck
