name:       generative-art
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:     David »quchen« Luposchainsky – dluposchainsky (λ) gmail
maintainer: David »quchen« Luposchainsky – dluposchainsky (λ) gmail
copyright:  "2018 David Luposchainsky"

extra-source-files:
    - README.md

description: Generative art using Haskell. See README.md.

dependencies:
    - base >= 4.7 && < 5

    - cairo
    - colour
    - containers
    - data-default-class
    - data-r-tree
    - mwc-random
    - random
    - text
    - tf-random
    - transformers
    - vector
    - deepseq

default-extensions:
    - BangPatterns
    - MultiWayIf
    - LambdaCase
    - RecordWildCards

extra-doc-files:
    - docs/bezier/1_single_curve.svg
    - docs/colors/schemes/continuous/**/*.png
    - docs/colors/schemes/discrete/**/*.svg
    - docs/geometry/cut/3_complicated.svg
    - docs/interpolation/3_simplify_path.svg
    - docs/geometry/convex_hull.svg
    - docs/geometry/point_in_polygon.svg
    - docs/interpolation/1_bezier_open.svg
    - docs/iso_lines/potentials.svg
    - docs/triangulation/3_haskell_logo.svg
    - docs/sampling/poisson-disc.svg
    - docs/billard/3_lambda.svg
    - docs/differential_equations/2_double_pendulum.svg
    - docs/differential_equations/1_two_body_problem.svg
    - docs/hexagonal/gaussian_hexagons.svg

ghc-options: [-Wall, -Wno-type-defaults]

library:
    source-dirs: src

executables:
    haskell-logo-billard:
        main:        Main.hs
        source-dirs: showcases/haskell_logo_billard
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
    haskell-logo-shattered:
        main:        Main.hs
        source-dirs: showcases/haskell_logo_shattered
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
    vector-fields:
        main: Main.hs
        source-dirs: showcases/vector_fields
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - Noise
    haskell-logo-voronoi:
        main: Main.hs
        source-dirs: showcases/haskell_logo_voronoi
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
        dependencies:
            - generative-art
            - Noise
    voronoi-interactive:
        main: Main.hs
        source-dirs: app/voronoi_interactive
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - threepenny-gui
            - temporary
    particle-shooter:
        main: Main.hs
        source-dirs: showcases/particle_shooter
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - parallel
    circuits:
        main: Main.hs
        source-dirs: showcases/circuits
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - parallel
    gray-scott:
        main: Main.hs
        source-dirs: showcases/gray_scott
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - accelerate
            - accelerate-llvm-native
            - parallel
            - comonad
            - JuicyPixels
            - JuicyPixels-extra
            - Noise

tests:
    testsuite:
        main:        Spec.hs
        source-dirs: test
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art

            - async
            - cairo
            - process
            - QuickCheck
            - random
            - tasty
            - tasty-hunit
            - tasty-quickcheck
            - transformers
            - directory
            - text
            - filepath
            - regex-tdfa
            - Glob
