name:       generative-art
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:     David »quchen« Luposchainsky – dluposchainsky (λ) gmail
maintainer: David »quchen« Luposchainsky – dluposchainsky (λ) gmail
copyright:  "2018 David Luposchainsky"

extra-source-files:
    - README.md

description: Generative art using Haskell. See README.md.

dependencies:
    - base >= 4.7 && < 5

    - cairo
    - colour
    - containers
    - data-default-class
    - data-r-tree
    - mwc-random
    - random
    - text
    - tf-random
    - transformers
    - vector
    - deepseq

default-extensions:
    - BangPatterns
    - MultiWayIf
    - LambdaCase
    - RecordWildCards

ghc-options: [-Wall, -Wno-type-defaults]

library:
    source-dirs: src

executables:
    haskell-logo-billard:
        main:        Main.hs
        source-dirs: showcases/haskell_logo_billard
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - cairo
    haskell-logo-triangles:
        main:        Main.hs
        source-dirs: showcases/haskell_logo_triangles
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - cairo
            - random
            - transformers
            - containers
    vector-fields:
        main: Main.hs
        source-dirs: showcases/vector_fields
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - cairo
            - Noise
            - mwc-random
    haskell-logo-voronoi:
        main: Main.hs
        source-dirs: showcases/haskell_logo_voronoi
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
        dependencies:
            - generative-art
            - cairo
            - mwc-random
            - Noise
    voronoi-interactive:
        main: Main.hs
        source-dirs: app/voronoi_interactive
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - cairo
            - threepenny-gui
            - mwc-random
            - temporary
    gauss-shooter:
        main: Main.hs
        source-dirs: app/gauss_shooter
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art
            - cairo
            - mwc-random
            - vector

tests:
    testsuite:
        main:        Spec.hs
        source-dirs: test
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - generative-art

            - async
            - cairo
            - process
            - QuickCheck
            - random
            - tasty
            - tasty-hunit
            - tasty-quickcheck
            - transformers
            - directory
            - text
            - filepath
            - regex-tdfa
