name:                generative-art
version:             0.1.0.0
github:              "githubuser/generative-art"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/generative-art#readme>

dependencies:
    - base >= 4.7 && < 5
    - cairo
    - colour
    - hsnoise
    - linear
    - MonadRandom
    - mtl
    - time
    - transformers
    - random

ghc-options:
    - -Wall

library:
  source-dirs: src

executables:
  generative-art-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -Wall
    dependencies:
        - generative-art
        - cairo
        - colour
        - hsnoise
        - linear
        - MonadRandom
        - mtl
        - time
        - transformers
        - random

tests:
  generative-art-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -Wall
    dependencies:
        - generative-art
        - cairo
        - colour
        - hsnoise
        - linear
        - MonadRandom
        - mtl
        - time
        - transformers
        - random
        - tasty
        - tasty-hunit
