name:       voronoi-3d
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:     Franz Thoma
maintainer: Franz Thoma
copyright:  "2022 Franz Thoma"

dependencies:
    - generative-art
    - base
    - cairo
    - mwc-random
    - Noise
    - vector

executables:
    voronoi-3d:
        main: Main.hs
        source-dirs: .
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
