name:       penplotting-circuits
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:
    - David Luposchainsky
copyright:
    - 2022 David Luposchainsky

default-extensions:
    - LambdaCase

dependencies:
    - generative-art
    - base
    - containers
    - data-default-class
    - deepseq
    - filepath
    - formatting
    - mwc-random
    - optparse-applicative
    - text

executables:
    penplotting-circuits:
        main: Main.hs
        source-dirs: .
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
