name:       circuits
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:
    - David Luposchainsky
copyright:
    - 2022 David Luposchainsky

default-extensions:
    - LambdaCase
    - RecordWildCards

dependencies:
    - generative-art
    - base
    - cairo
    - containers
    - deepseq
    - mwc-random
    - parallel
    - vector

executables:
    circuits:
        main: Main.hs
        source-dirs: .
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
