name:       haskell-logo-billard
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:     David »quchen« Luposchainsky – dluposchainsky (λ) gmail
copyright:  "2018 David Luposchainsky"

dependencies:
    - generative-art
    - base
    - cairo

default-extensions:
    - BangPatterns
    - LambdaCase
    - MultiWayIf
    - RecordWildCards

executables:
    haskell-logo-billard:
        main:        Main.hs
        source-dirs: .
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
